// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int n = Integer.parseInt(args[0]);
		int more = 0;
		int less = 0;

		for(int i=0; i<=n; i++){

			if(Math.random() <= 0.5){
				less += 1;
			}
		
			else {
				more += 1;
			}
		}

		System.out.println(" > 0.5: " + more + "times ");
		System.out.println(" <= 0.5: " + less + "times");
		double ratio = (double) more / (double) less;
		System.out.println(" ratio: "  + ratio);
	}
}
